version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "install dependencies"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello there!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere