version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "install dependencies"
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "hello"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere